[package]
name = "perf-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.21.2", features = ["full"] }
clap =  { version = "4.0.15", features = ["derive"] }
reqwest = "0.11.12"
tui = "0.19.0"
